### ISSUE TITLE
Uploading to a draft release

### ISSUE THREAD

**Issue by AriaMoradi** [AButler/upload-release-assets#10]
When you try to upload to a draft release it trows the error "Error: Not Found".

my case:
my workflow: https://github.com/AriaMoradi/Tachidesk/blob/d996c44b2425a7fc5fa00bba60e4953ef5e5aeed/.github/workflows/publish.yml
the failed action: https://github.com/AriaMoradi/Tachidesk/actions/runs/566468422

**Comment by portellaa** [comment]
Hi @AriaMoradi 
Just for clarification, i'm not a maintainer or contributor, but i think i can help on this.

A draft release doesn't have a tag associated and the action uses it to find the release associated.

I think in the current implementation of the action, you may not be able to achieve what you want, my two cents.

Again, i'm not a contributor, i just use the action so wait for an official answer 🙇

**Comment by AriaMoradi** [comment]
Currently I satisfy my workflow needs with 
```yml
      - name: Upload Release
        uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "master/repo/*"
          tags: true
          draft: true
          verbose: true
```
