### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by davidrunger** [AButler/upload-release-assets#18]
I am trying to use the recently-released v2.0.1 of this action, and I'm getting this error:

```
Error: Cannot find module '@actions/core'
Require stack:
- /__w/_actions/AButler/upload-release-assets/v2.0.1/lib/main.js
```

<details>
<summary>Click for full output</summary>

Link: https://github.com/davidrunger/skedjewel/actions/runs/3398042246/jobs/5650736420

```
Run AButler/upload-release-assets@v2.0.1
  with:
    files: skedjewel-v0.0.7.alpha2-linux
    repo-token: ***
    release-tag: v0.0.7.alpha2
/usr/bin/docker exec  63d14ab04227e818a74c16fd15d34d4c50e0de6680e1edba79af583ada85fae7 sh -c "cat /etc/*release | grep ^ID"
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /__w/_actions/AButler/upload-release-assets/v2.0.1/lib/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/__w/_actions/AButler/upload-release-assets/v2.0.1/lib/main.js:21:27)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/__w/_actions/AButler/upload-release-assets/v2.0.1/lib/main.js' ]
}
```
</details>

Here's how I'm using this action:

```yml
- name: Release
  uses: AButler/upload-release-assets@v2.0.1
  with:
    files: skedjewel-${{  github.ref_name }}-linux
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    release-tag: ${{  github.ref_name }}
```

<details>
<summary>Click for full GitHub Action workflow</summary>

Link: https://github.com/davidrunger/skedjewel/blob/v0.0.7.alpha2/.github/workflows/release.yml

```yml
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_upload_linux_binary:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: shards build --production --release --no-debug --static
      - name: Check version matches tag
        run: "[[ \"v$(bin/skedjewel --version)\" == ${{  github.ref_name }} ]] || exit 1"
      - name: Move and rename
        run: mv bin/skedjewel ./skedjewel-${{  github.ref_name }}-linux
      - name: Release
        uses: AButler/upload-release-assets@v2.0.1
        with:
          files: skedjewel-${{  github.ref_name }}-linux
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{  github.ref_name }}

  build_and_upload_macos_binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Build
        run: shards build --production --release --no-debug
      - name: Check version matches tag
        run: "[[ \"v$(bin/skedjewel --version)\" == ${{  github.ref_name }} ]] || exit 1"
      - name: Move and rename
        run: mv bin/skedjewel ./skedjewel-${{  github.ref_name }}-darwin
      - name: Release
        uses: AButler/upload-release-assets@v2.0.1
        with:
          files: skedjewel-${{  github.ref_name }}-darwin
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{  github.ref_name }}

```
</details>

Thanks in advance for anything you can do to help me resolve this error!
