### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by Borda** [AButler/upload-release-assets#44]
found it recently when using a private repo:
```yaml
    - name: Upload to release
      if: ${{ github.event_name == 'release' }}
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "dist/*"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```
and the error trace is:
```
Uploading dist/lit-0.0.8.dev0-py3-none-any.whl...
Error: Resource not accessible by integration
```
