### ISSUE TITLE
Question about setting file location(s)

### ISSUE THREAD

**Issue by Andre601** [AButler/upload-release-assets#5]
I currently have a task setup, which creates files and uploads those files to a site.
The generated files are created in the directory `build/libs`

I have a separate job, where I cd to this direction and zip all files. I consider switching to this action here, since the one I currently use (actions/upload-release-asset) has some errors and people there are quite slow at responding.

The question now is, how I would define the file(s) to use. Would it be relative to the current directory (which would be `build/libs` because of the cd) or relative to the project itself?

My current Workflow:
```yaml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Publish (Bintray)
      id: publish_bintray
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
      run: ./gradlew bintrayUpload
    #- name: Publish (GitHub Packages)
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    BUILD_NUMBER: 0 # Releases are always major.minor.revision_0
    #  run: ./gradlew publish
    - name: Zip files
      run: |
        cd build/libs
        zip release-${{ github.event.release.tag_name }} *.jar
    #
    # I want to replace this step
    #
    - name: Upload to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release-${{ github.event.release.tag_name }}.zip
        asset_name: release-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
```

**Comment by AButler** [comment]
The action should run with the working directory set to the repository root. You can set a working directory using the `working-directory` keyword ([see docs here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun)).

So it should be something like:

```yaml
- name: Zip files
      working-directory: ./build/libs
      run: zip release-${{ github.event.release.tag_name }} *.jar
- name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      with:
          files: './build/libs/release-${{ github.event.release.tag_name }}.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by Andre601** [comment]
I tried this, but I receive the following error:
```
##[error]No files found
##[error]Node run failed with exit code 1
```

My current workflow file:
```yaml
name: Publication task

on:
  release:
    types: [published]
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Publish (Bintray)
      id: publish_bintray
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
      run: ./gradlew bintrayUpload
    - name: Zip files
      working-directory: ./build/libs
      run: zip release-${{ github.event.release.tag_name }} *.jar
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: './build/libs/release-${{ github.event.release.tag_name }}.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  sendMessage:
    needs: [publish]
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: rjstone/discord-webhook-notify@v1
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        severity: info
        avatarUrl: 'https://raw.githubusercontent.com/botblock/JavaBotBlockAPI/master/src/main/resources/Jbba.png'
        username: 'New release (${{ github.event.release.tag_name }})'
        text: '${{ github.event.release.name }}'
        description: '[**Release Information**](${{ github.event.release.html_url }})'
        details: '${{ github.event.release.body }}'
        footer: 'Version ${{github.event.release.tag_name}}'
```

The zip action did find and zip the files according to the logs.
```
  adding: JavaBotBlockAPI-5.1.3-javadoc.jar (deflated 49%)
  adding: JavaBotBlockAPI-5.1.3-sources.jar (deflated 1%)
  adding: JavaBotBlockAPI-5.1.3.jar (deflated 1%)
```

**Comment by Andre601** [comment]
Minor update.
Changing it to the following workflow(s) made it upload the files. (Essentially removed the `./`)
```yaml
    - name: Zip files
      working-directory: ./build/libs
      run: zip release-${{ github.event.release.tag_name }} *.jar
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'build/libs/release-${{ github.event.release.tag_name }}.zip;build/libs/*.jar'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```

That said did a new weird issue appear, where the action ignores the zip file and only uploads the jar-files in the process.
No error or anything is thrown... Not even a mention that it can't find the file or attempts to upload it.

It only gives the following messages:
```
Uploading build/libs/JavaBotBlockAPI-5.1.4-javadoc.jar...
Uploading build/libs/JavaBotBlockAPI-5.1.4-sources.jar...
Uploading build/libs/JavaBotBlockAPI-5.1.4.jar...
```
