### ISSUE TITLE
Cannot upload assets for release which is being undefined

### ISSUE THREAD

**Issue by liudonghua123** [AButler/upload-release-assets#6]
I have a step like this:

```yaml
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: '/home/runner/work/github_actions/github_actions/dart-sdk-linux.tar.gz;/home/runner/work/github_actions/github_actions/depot_tools.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

But I got the following error.

```
 Run AButler/upload-release-assets@v2.01s
##[warning]Cannot upload assets for release which is being undefined
Run AButler/upload-release-assets@v2.0
  with:
    files: /home/runner/work/github_actions/github_actions/dart-sdk-linux.tar.gz;/home/runner/work/github_actions/github_actions/depot_tools.tar.gz
    repo-token: ***
##[warning]Cannot upload assets for release which is being undefined
```

I can confirm that I pushed a tag instead of a master commit.

**Comment by AButler** [comment]
The action is mainly set up for creating a GitHub release (which creates a tag) rather than on tag creation. Are you creating a GitHub release in a previous step?

**Comment by liudonghua123** [comment]
@AButler I did not create release in previous step.

**Comment by AButler** [comment]
Ah ok, thanks for the clarification. Currently this action only uploads assets to a release that already exists. I'll take a look at whether it makes sense to create a release if one does not exist already.

**Comment by mristin** [comment]
Hi @AButler ,
I'd like to confirm that I observe the same warning / error message (please see https://github.com/admin-shell-io/aasx-package-explorer/runs/986244151?check_suite_focus=true).

The release already exists and the action is triggered afterwards:
```
on:
  push:
    tags:
      - 'v*'
```

According to the documentation, the `action` should be there in `github.context.payload`:
https://developer.github.com/webhooks/event-payloads/#webhook-payload-object-common-properties

Maybe you can output the whole `github.context.payload` in case `github.context.payload` is null or undefined to facilitate bug reports?

**Comment by icemarkom** [comment]
Similar to @mristin, I just hit this in the workflow that had a release created from a tag. At the time this step was running, release existed.

**Comment by Ogerets** [comment]
same issue here

**Comment by D4VOS** [comment]
same issue in [my project](https://github.com/D4VOS/shadow-webdriver/blob/master/.github/workflows/release.yml)

**Comment by davidrunger** [comment]
I'm chiming in here in case it helps others. I was getting this error and then fixed it by using the `release-tag` option.

Here's how I am using this GitHub Action:

1. create a release manually through the GitHub web app; choose in the GitHub web app when doing so to have GitHub create a git tag for the release.
2. then, one of my Actions workflows is triggered by the creation of the release tag. That workflow builds release assets, which are uploaded using this action to the release that I just manually created.

I initially was getting this error

```
 Warning: Cannot upload assets for release which is being undefined
```

I fixed the error by adding the `release-tag` option for this GitHub Action:

```yml
- name: Release
  uses: AButler/upload-release-assets@v2.0
  with:
    files: skedjewel-${{  github.ref_name }}-linux
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    release-tag: ${{  github.ref_name }}
```

The value of `${{  github.ref_name }}` there is apparently the release tag. That might only be because of how the action is triggered; I'm not sure. Here's how the action is triggered:

```yml
on:
  push:
    tags:
      - "v*.*.*"
```

Now my release assets are uploading successfully. 👍

<details>
  <summary>For reference, click here to see my full GitHub Action workflow</summary>

Link: https://github.com/davidrunger/skedjewel/blob/v0.0.6/.github/workflows/release.yml
  
```yml
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_upload_linux_binary:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: shards build --production --release --no-debug --static
      - name: Check version matches tag
        run: "[[ \"v$(bin/skedjewel --version)\" == ${{  github.ref_name }} ]] || exit 1"
      - name: Move and rename
        run: mv bin/skedjewel ./skedjewel-${{  github.ref_name }}-linux
      - name: Release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: skedjewel-${{  github.ref_name }}-linux
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{  github.ref_name }}

  build_and_upload_macos_binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Build
        run: shards build --production --release --no-debug
      - name: Check version matches tag
        run: "[[ \"v$(bin/skedjewel --version)\" == ${{  github.ref_name }} ]] || exit 1"
      - name: Move and rename
        run: mv bin/skedjewel ./skedjewel-${{  github.ref_name }}-darwin
      - name: Release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: skedjewel-${{  github.ref_name }}-darwin
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{  github.ref_name }}
```
</details>
